services:
  # ---- Database ----
  db-init:
    image: postgres:17
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /var/lib/postgresql/data

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    image: postgres:17
    user: 2000:2000
    container_name: blockscout-db
    restart: always
    shm_size: 256m
    command:
      - -cmax_connections=200
      - -cclient_connection_check_interval=60000
    environment:
      POSTGRES_DB: blockscout
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: ceWb1MeLBEeOIfk65gU8EjF8
    ports:
      - "7432:5432"
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ---- Redis ----
  redis-db:
    image: redis:alpine
    container_name: blockscout-redis
    restart: always
    command: redis-server
    volumes:
      - ./redis-data:/data

  # ---- Blockscout Backend ----
  backend:
    depends_on:
      db:
        condition: service_healthy
      redis-db:
        condition: service_started
    image: ghcr.io/blockscout/blockscout:latest
    pull_policy: always
    container_name: blockscout-backend
    restart: always
    stop_grace_period: 5m
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:9547/
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:9547/
      ETHEREUM_JSONRPC_TRANSPORT: http
      ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: "false"
      CHAIN_ID: "10200200"
      DATABASE_URL: postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
      SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
      PORT: "4000"
      DISABLE_MARKET: "true"
      DISABLE_FILE_LOGGING: "false"
      ECTO_USE_SSL: "false"
      POOL_SIZE: "80"
      POOL_SIZE_API: "10"
      HEART_BEAT_TIMEOUT: "30"
      TXS_STATS_DAYS_TO_COMPILE_AT_INIT: "10"
      COIN_BALANCE_HISTORY_DAYS: "90"
      DECODE_NOT_A_CONTRACT_CALLS: "true"
      ACCOUNT_ENABLED: "false"
      ACCOUNT_REDIS_URL: redis://redis-db:6379
      API_V1_READ_METHODS_DISABLED: "false"
      API_V1_WRITE_METHODS_DISABLED: "false"
      RE_CAPTCHA_DISABLED: "false"
      ADMIN_PANEL_ENABLED: "false"
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      MICROSERVICE_SC_VERIFIER_ENABLED: "true"
      MICROSERVICE_SC_VERIFIER_URL: http://sc-verifier:8050/
      MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier
      MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: "false"
      MICROSERVICE_SIG_PROVIDER_ENABLED: "false"
      NFT_MEDIA_HANDLER_ENABLED: "false"
    tmpfs:
      - /tmp:size=256M
    volumes:
      - ./logs/:/app/logs/
      - ./solc-compilers/:/app/lib/explorer-9.0.2/priv/solc_compilers/

  # ---- Smart Contract Verifier ----
  sc-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:latest
    pull_policy: always
    platform: linux/amd64
    container_name: blockscout-sc-verifier
    restart: always

  # ---- Blockscout Frontend ----
  frontend:
    depends_on:
      - backend
    image: ghcr.io/blockscout/frontend:latest
    pull_policy: always
    platform: linux/amd64
    container_name: blockscout-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_HOST: localhost
      NEXT_PUBLIC_API_PORT: "4001"
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      NEXT_PUBLIC_NETWORK_NAME: Surge L2
      NEXT_PUBLIC_NETWORK_SHORT_NAME: Surge
      NEXT_PUBLIC_NETWORK_ID: "10200200"
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: xDAI
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: xDAI
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18"
      NEXT_PUBLIC_IS_TESTNET: "true"
      NEXT_PUBLIC_APP_HOST: localhost
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_APP_PORT: "4001"
      NEXT_PUBLIC_HOMEPAGE_CHARTS: "['daily_txs']"
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml

  # ---- Nginx Proxy ----
  proxy:
    depends_on:
      - backend
      - frontend
    image: nginx
    container_name: blockscout-proxy
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./proxy:/etc/nginx/templates
    environment:
      BACK_PROXY_PASS: http://backend:4000
      FRONT_PROXY_PASS: http://frontend:3000
    ports:
      - "4001:80"
